In [2]:
import numpy as np;

In [12]:
#creation of ndArray 
# 1) from LIST 
array = np.array([1,2,3,4,5]);
print(array,type(array))

print('\n')

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2,type(arr2),arr2.shape)

print("\n")

arr3= np.array([2,5,2,"Name"])
print(arr3,type(arr3),arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>


[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


['2' '5' '2' 'Name'] <class 'numpy.ndarray'> (4,)


In [18]:
#using built in functions to make an array
arr4= np.zeros((2,4),dtype="int64")
print(arr4 , "\n")

arr5= np.ones((3,4),dtype=int)
print(arr5,"\n")

arr6 = np.eye(4)
print(arr6,"\n")

arr7=np.full((3,5),7)
print(arr7,"\n")

print(np.arange(1,15,3))
print(np.linspace(1,9,5))

[[0 0 0 0]
 [0 0 0 0]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]] 

[ 1  4  7 10 13]
[1. 3. 5. 7. 9.]


In [20]:
#array properties 
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#------------------------------------------------------------
print(f"The shape of the elements are {arr.shape}")
print("The total elements are ",arr.size)
print("data type of the elements is",arr.dtype)
print("The sieze of each element is ",arr.itemsize)
print("The dimension of the array is ",arr.ndim)
#-------------------------------------------------------------

The shape of the elements are (4, 3)
The total elements are  12
data type of the elements is int64
The sieze of each element is  8
The dimension of the array is  2


In [24]:
#explicitly changing the array types 
print(np.array(["Abhishek"],dtype="U"))
arr4 = arr4.astype(np.float64)
print(arr4)

['Abhishek']
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# operations on Array 
arr = np.array([1,2,3,4,5,6])
arrNew = arr.reshape((2,3))
print(arrNew,arrNew.dtype,arrNew.ndim,arrNew.shape,arrNew.size);

flattenArray = arrNew.flatten()
print(flattenArray)

[[1 2 3]
 [4 5 6]] int64 2 (2, 3) 6
[1 2 3 4 5 6]


In [34]:
print(arr[0])

idx = [1,3]
print(arr[idx])

a = np.array([10, 20,57 ,30, 40, 50])
mask = a> 20
print(a[mask])
print(mask)
print(a[a%2 ==0])
print(a[(a>=20) & (a<40)])

1
[2 4]
[57 30 40 50]
[False False  True  True  True  True]
[10 20 30 40 50]
[20 30]


In [37]:
#slicing and copy 
a1=np.array([1,5,2,00,8])
a2=a1[1:3].copy()
a2[0]=999
a3 = a2[:] # this returns a view 
print(a3)
print(a1)
print(a2)

[999   2]
[1 5 2 0 8]
[999   2]
